---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# images:
#   - name: mcrute/ses-smtpd-proxy
#     newTag: 0.2.0

resources:
- ./deployment.yaml
- ./service.yaml
- ./serviceaccount.yaml
